image: Visual Studio 2017

clone_depth: 1

platform:
  - Win32

configuration:
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - git submodule update --init --recursive
  - SET PATH=C:\msys64\usr\bin;%PATH%
  - SET PATH=C:\msys64\mingw64\bin;%PATH%
  - pacman --noconfirm -S mingw64/mingw-w64-x86_64-python3-pip
  # copy the libdl.a from cgwin
  - cp C:\cygwin64\lib\libdl.a C:\msys64\mingw64\lib\libdl.a
  - python --version
  - python -m pip install wheel
  # remove sh file so that make won't complain
  - rm "C:/Program Files/Git/usr/bin/sh.exe"

build_script:
  - pip install .
  - pip install pytest

test_script:
  - pytest tests/

