image: Visual Studio 2019

clone_depth: 1

platform:
  - Win32

configuration:
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version

install:
  - git submodule update --init --recursive
  - SET PATH=C:\\Python37-x64;C:\\Python37-x64\\Scripts;%PATH%
  - python --version
  - python -m pip install wheel cmake

build_script:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - python setup.py bdist_wheel
  - pip install pytest

test_script:
  - pytest tests/

