image: Visual Studio 2017

clone_depth: 1

platform:
  - Win32

configuration:
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - git submodule update --init --recursive
  - SET PATH=C:\msys64\usr\bin;%PATH%
  - SET PATH=C:\msys64\mingw64\bin;%PATH%
  - pacman --noconfirm -S mingw64/mingw-w64-x86_64-python3-pip
  # install verilator
  - pacman --noconfirm -S mingw-w64-x86_64-verilator
  # copy the libdl.a from cgwin
  - cp C:\cygwin64\lib\libdl.a C:\msys64\usr\lib\libdl.a
  - python --version
  - python -m pip install wheel
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - verilator --version
  # remove sh file so that make won't complain
  - rm "C:/Program Files/Git/usr/bin/sh.exe"

build_script:
  - python setup.py bdist_wheel
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - pip install pytest

test_script:
  - pytest tests/

