matrix:
    include:
        - name: "Linux"
          services:
            - docker
          language: minimal
        - name: "macOS"
          os: osx
          language: shell
          osx_image: xcode11
        - name: "Windows"
          os: windows
          language: shell
          compiler: gcc
          before_install:
            - choco install python
          env: PATH=/c/MinGW/bin:/c/Python37:/c/Python37/Scripts:$PATH

script:
    - ./scripts/ci.sh

deploy:
  - provider: script
    script: /bin/sh scripts/deploy.sh
    on:
      branch: master
      tags: true
