matrix:
    include:
        - name: "Linux"
          services:
            - docker
          language: minimal
          env: BUILD_WHEEL=true
        - name: "Linux ctest"
          services:
            - docker
          language: minimal
          env: BUILD_WHEEL=false
        - name: "Linux clang-tidy"
          services:
            - docker
          language: minimal
          env: USE_CLANG_TIDY
        - name: "macOS"
          os: osx
          language: shell
          osx_image: xcode10.1

script:
    - ./scripts/ci.sh

deploy:
  - provider: script
    script: /bin/bash scripts/deploy.sh
    on:
      branch: master
      tags: true
