matrix:
    include:
        - name: "Linux pytest"
          services:
            - docker
          language: minimal
          env:
            - BUILD_WHEEL=true
            - OS=linux


script:
    - ./scripts/ci.sh

deploy:
  - provider: script
    script: /bin/bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      tags: true
