version: '{build}'
image: Visual Studio 2015

build: off
# copied some commands from https://framagit.org/simgrid/simgrid/blob/master/.appveyor.yml
build_script:
- cmd: ls
- cmd: git submodule init
- cmd: git submodule update
- cmd: SET PATH=C:\Python37-x64;%PATH% # We need python3
- cmd: python --version
- cmd: python -m pip install wheel
# Use the mingw-w64 provided by Appveyor
- cmd: SET PATH=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\;%PATH%

# not using sh.exe otherwise mingw will die
- rename "C:\Program Files\Git\usr\bin\sh.exe" "sh-ignored.exe"
- cmd: python setup.py bdist_wheel

test: off

artifacts:
    - path: dist/*.whl
